<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260623205657 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the books table.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE books (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, serial_number VARCHAR(6) NOT NULL, title VARCHAR(255) NOT NULL, author VARCHAR(255) NOT NULL, borrowed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, borrowed_by_card_number VARCHAR(6) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4A1B2A92D948EE2 ON books (serial_number)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE books');
    }
}
